version: "3"

services:
  react-server:
    container_name: react-server
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - "REACT_APP_API_URL=http://localhost:3001"
    ports:
      - "3000:8080"
